### ISSUE TITLE
Error: Cannot find ffmpeg

### ISSUE THREAD

**Issue by Jougan** [simplymemes/crunchyroll-dl#13]
i crunchyroll-dl v1.2.1
i Attempting to login...
i Successfully logged in!
i Logged in with a premium account.
i Attempting to fetch episode...
i Downloading episode as "BORUTO NARUTO NEXT GENERATIONS Episode 99 [1080p].mp4"
(node:1192) UnhandledPromiseRejectionWarning: Error: Error: Cannot find ffmpeg
    at FfmpegCommand.ffmpeg.on.on.on.error (C:\Users\AppData\Roaming\npm\node_modules\crunchyroll-dl\index.js:434:16)
    at FfmpegCommand.emit (events.js:160:13)
    at emitEnd (C:\Users\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\fluent-ffmpeg\lib\processor.js:424:16)
    at C:\Users\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\fluent-ffmpeg\lib\processor.js:433:16
    at C:\Users\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\async\dist\async.js:473:16
    at next (C:\Users\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\async\dist\async.js:5329:29)
    at C:\Users\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\async\dist\async.js:969:16
    at C:\Users\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\async\dist\async.js:473:16
    at next (C:\Users\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\async\dist\async.js:5329:29)
    at C:\Users\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\async\dist\async.js:969:16
(node:1192) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:1192) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
i Logging out...

**Comment by adriannx** [comment]
I have the same issue, anyone can help pls?
