### ISSUE TITLE
 UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined

### ISSUE THREAD

**Issue by Abu3safeer** [simplymemes/crunchyroll-dl#16]
Hello everyone, I have this issue:
```
(node:4176) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at getEpisode (C:\Users\*******\AppData\Roaming\npm\node_modules\crunchyroll-dl\index.js:240:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:4176) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:4176) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
```

This is the code:
```
>crunchyroll-dl --username *** --password **** --language arME --quality 1080p --output ":name - :ep [:resolution]" --input https://www.crunchyroll.com/ar/bono-bono
```

I can access this episode from browser.

**Comment by simplymemes** [comment]
Are you in the latest version?

**Comment by Abu3safeer** [comment]
Yes 1.3.3
This issue happens only with this anime, I don't know why.
Other animes work just fine.

**Comment by Noctunus** [comment]
@Abu3safeer Just a wild guess but did you try the non-regional (/US) link? -> https://www.crunchyroll.com/bono-bono

**Comment by Abu3safeer** [comment]
No, I just copy the link, I didn't have any issues before with links in this app, so I never tried it.

**Comment by Abu3safeer** [comment]
@Noctunus Same thing, just tried it now.

**Comment by simplymemes** [comment]
@Abu3safeer Can you post the entire output of the log (starting from the `crunchyroll-dl v1.3.3` line) to a website such as https://gist.github.com and send it?

**Comment by Abu3safeer** [comment]
```
i crunchyroll-dl v1.3.2
i Attempting to login...
i Successfully logged in!
i Logged in with a premium account.
? Current session expires on Wed May 15 2019 09:58:31 GMT-0700 (Pacific Daylight Time)
i Attempting to fetch series...
? Attempting to fetch https://www.crunchyroll.com/bono-bono
? Filtered collections: "BONO BONO"," BONO BONO 2nd Season"," BONO BONO 3rd Season"
√ Which collections would you like to download? » BONO BONO, BONO BONO 2nd Season, BONO BONO 3rd Season
i Beginning to download "BONO BONO"
i Downloading episode 1, "البحر مكانٌ تلعب فيه وحيداً", of "BONO BONO"
i Attempting to fetch episode...
? Found 0 streams
! You may not have access to watch this episode
(node:5264) UnhandledPromiseRejectionWarning: TypeError: Cannot read property 'url' of undefined
    at getEpisode (C:\Users\*****\AppData\Roaming\npm\node_modules\crunchyroll-dl\index.js:240:33)
    at process._tickCallback (internal/process/next_tick.js:68:7)
(node:5264) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:5264) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.
i Logging out...
```

![image](https://user-images.githubusercontent.com/12091003/56151075-1ce6ff80-5fb9-11e9-8132-51932ccf1b2c.png)

**Comment by Abu3safeer** [comment]
Oh, I just noticed that I cannot watch this episode on my phone, could it be there is no hardsub version on this anime? 

I am so sorry, I should have tested that before asking this question.

**Comment by simplymemes** [comment]
@Abu3safeer From that, I see that you're still using v1.3.2... But I will push a fix for this error showing up at least in the next update, when I figure out something else I want to add.

A good way to test if an episode works with this app, however, would be if you use https://github.com/destruc7i0n/nani
I used a lot of his code as a baseline for this...

**Comment by Abu3safeer** [comment]
Oh, sorry, I have it updated on my device, looks like I forgot to update it in the other machine.

**Comment by Abu3safeer** [comment]
```
i crunchyroll-dl v1.3.3
i Attempting to login...
i Successfully logged in!
i Logged in with a premium account.
i Attempting to fetch series...
√ Which collections would you like to download? » BONO BONO, BONO BONO 2nd Season, BONO BONO 3rd Season
i Beginning to download "BONO BONO"
i Downloading episode 1, "البحر مكانٌ تلعب فيه وحيداً", of "BONO BONO"
i Attempting to fetch episode...
! You may not have access to watch this episode
i Downloading episode 2, "ضرسي يؤلمني، يؤلمني بشدّة", of "BONO BONO"
i Attempting to fetch episode...
! You may not have access to watch this episode
i Downloading episode 3, "أريد تسلّق شجرة", of "BONO BONO"
i Attempting to fetch episode...
! You may not have access to watch this episode
i Downloading episode 4, "أين كلب البراري؟", of "BONO BONO"
i Attempting to fetch episode...
! You may not have access to watch this episode
i Downloading episode 5, "الأحلام غريبة", of "BONO BONO"
i Attempting to fetch episode...
i Downloading episode as "BONO BONO - 5 [1080p].mp4"
i Beginning download...
i Downloading... 86.34% 212/fps 00:04:44.91/encoded
```

You are right, if it has no access, it will skip the episode.
Sorry for the inconvenience.
