### ISSUE TITLE
Download stop working

### ISSUE THREAD

**Issue by theruleof4** [simplymemes/crunchyroll-dl#45]
After the unblock problem, another one:

(node:9508) UnhandledPromiseRejectionWarning: TypeError: Cannot read property '0' of undefined
    at /media/sdc1/user/lib/node_modules/crunchyroll-dl/index.js:640:37
    at processTicksAndRejections (internal/process/task_queues.js:85:5)
    at async Promise.all (index 0)
    at async main (/media/sdc1/user/lib/node_modules/crunchyroll-dl/index.js:642:28)
(node:9508) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 1)
(node:9508) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code.

Any ideas?

**Comment by simplymemes** [comment]
Can you post the command/series you were downloading?

**Comment by theruleof4** [comment]
crunchyroll-dl -i https://www.crunchyroll.com/my-hero-academia/episode-1-izuku-midoriya-origin-730707 -u user@gmail.com -p password --ignore-dubs -s soft --language ptBR --mux=false -o ":epname [:resolution]"

**Comment by AlexIsOK** [comment]
Are you sure the subtitles for that show are available in that language?  I tried this with my own account and got an error.  When I changed ptBR to enUS the download worked normally(ish).

`crunchyroll-dl -i https://www.crunchyroll.com/my-hero-academia/episode-1-izuku-midoriya-origin-730707 -u username -p passwd --ignore-dubs -s soft --mux false --language enUS -o ":epname [:resolution]" --vilos`

I had to use the --vilos parameter, soft subs wouldn't work otherwise.

**Comment by theruleof4** [comment]
Yes It's available, English, Spanish and Portuguese. In this page of the episode its described

**Comment by AlexIsOK** [comment]
Odd... Are you using a VPN or proxy that goes outside of Brazil?  The Brazilian subtitles are not available in the United States.

**Comment by andrewx2020** [comment]
The problem is that there is no longer a "stream_data" field in the Media type. It seems to have been replaces with a bif_url that points to something on vrv. I have no been able to understand it yet.
