### ISSUE TITLE
Cannot solve CAPTCHA automatically! Please try again later.

### ISSUE THREAD

**Issue by Kanekid2m** [simplymemes/crunchyroll-dl#52]
Got this issue today because of Cloudfare Protection and captcha. Hope you can fix it!

`i crunchyroll-dl v2.0.1
i Attempting to login...
i Successfully logged in!
i Logged in with a premium account.
i Attempting to fetch series...
! Error fetching series: captcha
! Cannot solve CAPTCHA automatically! Please try again later.
i Logging out...
Unhandled rejection CaptchaError: captcha
    at validateResponse (C:\Users\D2M\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\cloudscraper\index.js:273:11)
    at onCloudflareResponse (C:\Users\D2M\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\cloudscraper\index.js:222:5)
    at onRequestResponse (C:\Users\D2M\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\cloudscraper\index.js:205:5)
    at Request.<anonymous> (C:\Users\D2M\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\cloudscraper\index.js:149:7)
    at Object.onceWrapper (events.js:422:26)
    at Request.emit (events.js:315:20)
    at Request.<anonymous> (C:\Users\D2M\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\request\request.js:1154:10)
    at Request.emit (events.js:315:20)
    at Gunzip.<anonymous> (C:\Users\D2M\AppData\Roaming\npm\node_modules\crunchyroll-dl\node_modules\request\request.js:1076:12)
    at Object.onceWrapper (events.js:421:28)
    at Gunzip.emit (events.js:315:20)
    at endReadableNT (_stream_readable.js:1218:12)
    at processTicksAndRejections (internal/process/task_queues.js:84:21)`

**Comment by TrashBandatcoot** [comment]
Yeah, I have the same issue, this seems to be just another attempt at Crunchyroll trying to break CR-dl.

**Comment by rhennanxkz** [comment]
api down, expect them to find another way

**Comment by Zei33** [comment]
This is still an issue. It is occurring specifically when a series URL is provided instead of a specific episode URL.
