### ISSUE TITLE
Unhandled Promise Error 403

### ISSUE THREAD

**Issue by rvishwajith** [simplymemes/crunchyroll-dl#57]
I got this error

```
 % crunchyroll-dl -i https://www.crunchyroll.com/demon-slayer-kimetsu-no-yaiba/episode-19-hinokami-786932 -u [REDACTED] -p [REDACTED] -s soft --language enUS
i crunchyroll-dl v2.0.1
i Attempting to login...
i Successfully logged in!
i Attempting to fetch episode...
(node:2852) UnhandledPromiseRejectionWarning: Error: Request failed with status code 403
    at createError (/usr/local/lib/node_modules/crunchyroll-dl/node_modules/axios/lib/core/createError.js:16:15)
    at settle (/usr/local/lib/node_modules/crunchyroll-dl/node_modules/axios/lib/core/settle.js:17:12)
    at IncomingMessage.handleStreamEnd (/usr/local/lib/node_modules/crunchyroll-dl/node_modules/axios/lib/adapters/http.js:236:11)
    at IncomingMessage.emit (events.js:214:15)
    at endReadableNT (_stream_readable.js:1178:12)
    at processTicksAndRejections (internal/process/task_queues.js:80:21)
(node:2852) UnhandledPromiseRejectionWarning: Unhandled promise rejection. This error originated either by throwing inside of an async function without a catch block, or by rejecting a promise which was not handled with .catch(). (rejection id: 2)
(node:2852) [DEP0018] DeprecationWarning: Unhandled promise rejections are deprecated. In the future, promise rejections that are not handled will terminate the Node.js process with a non-zero exit code
```

Not sure what the solution is, the other 403 issue was unrelated from what I can tell.

**Comment by Noctunus** [comment]
Sorry I got no solution for you but only a hint: You should *really* mask your username/password.

**Comment by rvishwajith** [comment]
Oops my bad. Fixed it.

**Comment by Gurkward** [comment]
Yea sorry same as Noctunus, got no solotuion but we can still access the unedited version of the issue, so make sure to change it asap if you haven't already, on all services you've used it on ofc.

**Comment by rvishwajith** [comment]
Thanks it should be gone for good.
